// Built-in starter library, used before (or without) an API key.
const SITES = {
  "Weird & wonderful":["🌀",[
    ["The Useless Web","https://theuselessweb.com","A button that sends you to a pointless website. Stumbling, inside stumbling."],
    ["Pointer Pointer","https://pointerpointer.com","Leave your cursor anywhere and a real photo of someone pointing at it appears."],
    ["Staggering Beauty","https://www.staggeringbeauty.com","Wiggle your mouse. Then wiggle it faster. (Flashing lights warning.)"],
    ["Hacker Typer","https://hackertyper.net","Mash your keyboard and look like a movie hacker."],
    ["Zoomquilt","https://zoomquilt.org","An endless painted zoom that never reaches the bottom."],
    ["Koalas to the Max","https://koalastothemax.com","Hover over circles to split them until a picture emerges."],
    ["Eel Slap","https://eelslap.com","Exactly what it says. Move your mouse to slap a man with an eel."],
    ["Cameron's World","https://www.cameronsworld.net","A collage of GeoCities pages, glitter GIFs and all."],
    ["Windows 93","https://www.windows93.net","A fake operating system full of jokes and tiny programs."],
    ["Paper Planes","https://paperplanes.world","Fold a paper plane, stamp it with your location, and throw it to a stranger."],
    ["Pixel Thoughts","https://www.pixelthoughts.co","Put a worry in a star and watch it shrink away over 60 seconds."],
    ["Falling Falling","https://www.fallingfalling.com","An endless falling animation with a hypnotic soundtrack."],
    ["Bees & Bombs","https://beesandbombs.com","Mesmerizing looping geometric animations."],
    ["Pug in a Rug","https://puginarug.com","A pug. In a rug. That is the whole site."],
    ["Long Doge Challenge","https://longdogechallenge.com","Scroll to see how long the dog gets."],
    ["Hooooooooo","https://hooooooooo.com","An owl that hoots. Keep scrolling right."],
    ["Rotating Sandwiches","https://rotatingsandwiches.com","A gallery of sandwiches, slowly rotating."],
    ["Is It Christmas?","https://isitchristmas.com","Answers one question, every day of the year."]]],
  "Music":["🎧",[
    ["Radio Garden","https://radio.garden","Spin a globe and tune into live radio stations anywhere on Earth."],
    ["Radiooooo","https://radiooooo.com","Choose a country and a decade, then listen to what was playing."],
    ["Every Noise at Once","https://everynoise.com","A map of thousands of music genres you can click to hear."],
    ["Chrome Music Lab","https://musiclab.chromeexperiments.com","Playful experiments for making and understanding music."],
    ["Incredibox","https://www.incredibox.com","Drag sounds onto a beatboxing crew to build a track."],
    ["Musicmap","https://musicmap.info","A genealogy of popular music genres, with example tracks."],
    ["Patatap","https://patatap.com","Every key on your keyboard makes a sound and an animation."],
    ["WhoSampled","https://www.whosampled.com","Trace which songs sampled, covered, or remixed which."],
    ["Typatone","https://typatone.com","Type a sentence and hear it turned into a melody."],
    ["Ishkur's Guide to Electronic Music","https://music.ishkur.com","A sprawling, opinionated map of electronic music genres with samples."],
    ["Online Sequencer","https://onlinesequencer.net","Make music in your browser and remix thousands of user tracks."],
    ["Learning Synths","https://learningsynths.ableton.com","Learn how synthesizers work by playing with one."],
    ["Learning Music","https://learningmusic.ableton.com","Ableton's playful lessons on beats, melody and song structure."],
    ["Drumbit","https://drumbit.app","A tiny drum machine you can program in seconds."],
    ["Bandcamp Daily","https://daily.bandcamp.com","Writing about independent music from every corner of the world."],
    ["Earth.fm","https://earth.fm","Nature recordings from forests, oceans and deserts, mapped."],
    ["Radio Aporee","https://aporee.org/maps/","A map of field recordings from thousands of places."],
    ["NTS Radio","https://www.nts.live","Live radio from London and LA with very eclectic shows."]]],
  "Film & TV":["🎞️",[
    ["Film-Grab","https://film-grab.com","A huge archive of beautiful stills, browsable by film."],
    ["Art of the Title","https://www.artofthetitle.com","Deep dives into film and TV title sequences."],
    ["IMSDb","https://imsdb.com","Read the scripts of hundreds of movies."],
    ["Prelinger Archives","https://archive.org/details/prelinger","Ephemeral films: ads, educational shorts, and industrial reels."],
    ["Feature Films on the Internet Archive","https://archive.org/details/feature_films","Public domain features you can watch right now."],
    ["Criterion Closet Picks","https://www.criterion.com/closet-picks","Directors and actors raid the Criterion closet and explain their picks."],
    ["Senses of Cinema","https://www.sensesofcinema.com","A long-running online journal of serious film writing."],
    ["Bright Lights Film Journal","https://brightlightsfilm.com","Film criticism with a taste for the offbeat."],
    ["Movie-Map","https://www.movie-map.com","Type a film you like and see similar ones float around it."],
    ["TV Tropes","https://tvtropes.org","A bottomless wiki of storytelling patterns. Clear your afternoon."],
    ["Script Slug","https://www.scriptslug.com","Read screenplays from films and TV shows, free."],
    ["MUBI Notebook","https://mubi.com/notebook","Essays and interviews about cinema from around the world."],
    ["Free Movies at Open Culture","https://www.openculture.com/freemoviesonline","Hundreds of classic and indie films you can watch free."]]],
  "Art & design":["🎨",[
    ["The Public Domain Review","https://publicdomainreview.org","Essays and oddities from the history of art, literature and ideas."],
    ["Sanzo Wada's Color Combinations","https://sanzo-wada.dmbk.io","A 1930s Japanese color dictionary, made interactive."],
    ["Fonts In Use","https://fontsinuse.com","An archive of typography spotted in the wild."],
    ["Weave Silk","http://weavesilk.com","Draw with symmetrical, flowing strands of light."],
    ["Quick, Draw!","https://quickdraw.withgoogle.com","Doodle something and a neural network tries to guess it."],
    ["Google Arts & Culture","https://artsandculture.google.com","Museum collections, zoomable artworks and odd experiments."],
    ["Cooper Hewitt Collection","https://collection.cooperhewitt.org","Browse the Smithsonian's design museum, even by color."],
    ["This Is Sand","https://thisissand.com","Pour colored sand into slow, satisfying layered pictures."],
    ["The Met Collection","https://www.metmuseum.org/art/collection","Search hundreds of thousands of artworks from the Met."],
    ["Smithsonian Open Access","https://www.si.edu/openaccess","Millions of free images from Smithsonian museums."],
    ["Typewolf","https://www.typewolf.com","What fonts real websites are using, and why they work."],
    ["Font Review Journal","https://fontreviewjournal.com","Thoughtful reviews of typefaces, like book reviews for fonts."],
    ["Coolors","https://coolors.co","Hit the spacebar to generate color palettes."],
    ["COLOURlovers","https://www.colourlovers.com","A community archive of colors, palettes and patterns."],
    ["Hyperallergic","https://hyperallergic.com","Sharp, independent writing about art and culture."]]],
  "Science & space":["🔭",[
    ["Scale of the Universe","https://htwins.net/scale2/","Zoom from the Planck length to the whole observable universe."],
    ["If the Moon Were One Pixel","https://joshworth.com/dev/pixelspace/pixelspace_solarsystem.html","Scroll across a to-scale solar system. It takes a while."],
    ["The Deep Sea","https://neal.fun/deep-sea/","Scroll down into the ocean and meet what lives at each depth."],
    ["Astronomy Picture of the Day","https://apod.nasa.gov","A new space image every day since 1995, with an explanation."],
    ["Earth Wind Map","https://earth.nullschool.net","Live wind, ocean currents and weather swirling around the globe."],
    ["Stellarium Web","https://stellarium-web.org","A planetarium in your browser showing tonight's sky."],
    ["Bartosz Ciechanowski","https://ciechanow.ski","Stunning interactive explainers on how things work."],
    ["Explorable Explanations","https://explorabl.es","A collection of learn-by-playing interactive essays."],
    ["Our World in Data","https://ourworldindata.org","Clear charts on how the world is changing, on almost any topic."],
    ["Eyes on the Solar System","https://eyes.nasa.gov/apps/solar-system/","NASA's 3D solar system with real spacecraft positions."],
    ["Nicky Case","https://ncase.me","Playable explainers on trust, voting, anxiety and more."],
    ["Seeing Theory","https://seeing-theory.brown.edu","Probability and statistics, explained visually."],
    ["PhET Simulations","https://phet.colorado.edu","Free physics, chemistry and math simulations to play with."],
    ["Light Pollution Map","https://www.lightpollutionmap.info","Find the darkest skies near you."],
    ["Zooniverse","https://www.zooniverse.org","Help real scientists by classifying galaxies, animals and more."],
    ["Quanta Magazine","https://www.quantamagazine.org","Beautifully written stories about math, physics and biology."],
    ["Blitzortung Lightning Maps","https://www.lightningmaps.org","Lightning strikes around the world, as they happen."]]],
  "Nostalgia":["📼",[
    ["The Restart Page","https://www.therestartpage.com","Old operating systems rebooting, one after another."],
    ["Space Jam (1996)","https://www.spacejam.com/1996/","The original movie website, still preserved as it was."],
    ["Museum of Endangered Sounds","https://savethesounds.info","Dial-up modems, Tamagotchis and other vanishing noises."],
    ["oldweb.today","https://oldweb.today","Browse archived websites through emulated old browsers."],
    ["Poolsuite FM","https://poolsuite.net","Summery radio inside a retro desktop interface."],
    ["Wayback Machine","https://web.archive.org","Look up any website as it was years ago."],
    ["Chronicling America","https://chroniclingamerica.loc.gov","Historic American newspapers, searchable page by page."],
    ["Old Maps Online","https://www.oldmapsonline.org","Find historical maps of anywhere you've ever lived."],
    ["Wiby","https://wiby.me","A search engine for old-school, simple personal web pages."],
    ["Neocities","https://neocities.org/browse","Browse handmade personal websites in the GeoCities spirit."],
    ["GifCities","https://gifcities.org","Search millions of animated GIFs rescued from GeoCities."],
    ["PCjs Machines","https://www.pcjs.org","Run vintage IBM PCs and old software in your browser."],
    ["Museum of Obsolete Media","https://obsoletemedia.org","Every forgotten tape, disc and cartridge format, catalogued."],
    ["OldComputers.net","https://oldcomputers.net","A museum of home computers from the 70s and 80s."],
    ["The Old Net","https://theoldnet.com","Visit archived websites as they looked in the 90s."]]],
  "Travel & places":["🧭",[
    ["WindowSwap","https://www.window-swap.com","Look out a stranger's window somewhere in the world."],
    ["Drive & Listen","https://drivenlisten.com","Ride through a city's streets with its local radio on."],
    ["City Walks","https://citywalks.live","Walk through cities around the world, in real footage."],
    ["Earth View","https://earthview.withgoogle.com","Striking satellite images of the planet's landscapes."],
    ["Atlas Obscura","https://www.atlasobscura.com","The world's hidden wonders and strange places."],
    ["Cities and Memory","https://citiesandmemory.com","A global sound map of field recordings and their reimaginings."],
    ["Virtual Vacation","https://virtualvacation.us","Walk, drive or fly through places around the world."],
    ["MapCrunch","https://www.mapcrunch.com","Drop into a random Street View anywhere on Earth."],
    ["Ancient Earth Globe","https://dinosaurpictures.org/ancient-earth","See where your town was 600 million years ago."],
    ["The True Size Of","https://thetruesize.com","Drag countries around the map to see their real size."],
    ["Native Land","https://native-land.ca","A map of Indigenous territories, languages and treaties."],
    ["Flightradar24","https://www.flightradar24.com","Watch every plane in the sky, live."],
    ["MarineTraffic","https://www.marinetraffic.com","Every ship at sea, tracked in real time."]]],
  "Food":["🍓",[
    ["Gastro Obscura","https://www.atlasobscura.com/gastro","Unusual foods, drinks, and culinary history."],
    ["TasteAtlas","https://www.tasteatlas.com","A world map of traditional dishes and where they come from."],
    ["The Food Timeline","https://www.foodtimeline.org","When and where foods and recipes first appeared."],
    ["Supercook","https://www.supercook.com","Enter what's in your kitchen and find recipes that use it."],
    ["Serious Eats","https://www.seriouseats.com","Recipes with the science of why they work."],
    ["Cooking for Engineers","https://www.cookingforengineers.com","Recipes broken down into precise, diagrammed steps."],
    ["Smitten Kitchen","https://smittenkitchen.com","A home cook's long-running blog of reliable recipes."],
    ["Just the Recipe","https://www.justtherecipe.com","Paste a recipe link and get just the recipe, no life story."],
    ["Difford's Guide","https://www.diffordsguide.com","A huge, careful encyclopedia of cocktails."],
    ["Wine Folly","https://winefolly.com","Wine explained simply, with lovely charts."],
    ["Cheese.com","https://www.cheese.com","Look up nearly 2,000 cheeses by texture, milk and country."],
    ["Feeding America","https://d.lib.msu.edu/fa","Historic American cookbooks, digitized and readable."]]],
  "Games & play":["🎲",[
    ["Little Alchemy 2","https://littlealchemy2.com","Combine elements to discover hundreds of things."],
    ["Universal Paperclips","https://www.decisionproblem.com/paperclips/","Make paperclips. Then make more. It gets out of hand."],
    ["A Dark Room","https://adarkroom.doublespeakgames.com","A minimalist text adventure that keeps unfolding."],
    ["The Password Game","https://neal.fun/password-game/","Create a password that follows increasingly absurd rules."],
    ["Spend Bill Gates' Money","https://neal.fun/spend/","Try to spend a few billion dollars."],
    ["Slow Roads","https://slowroads.io","An endless, calming procedurally generated drive."],
    ["Semantle","https://semantle.com","Guess the secret word by how close in meaning you get."],
    ["2048","https://play2048.co","Slide tiles, merge numbers, lose an afternoon."],
    ["Sandboxels","https://sandboxels.r74n.com","A falling-sand game with hundreds of elements to mix."],
    ["Candy Box 2","https://candybox2.github.io","A tiny ASCII adventure that starts with a single candy."],
    ["Cookie Clicker","https://orteil.dashnet.org/cookieclicker/","Click a cookie. Then build a cookie empire."],
    ["Contexto","https://contexto.me","Find the secret word by how close your guesses are in meaning."],
    ["Worldle","https://worldle.teuteuf.fr","Guess the country from its silhouette."],
    ["Simon Tatham's Puzzles","https://www.chiark.greenend.org.uk/~sgtatham/puzzles/","Dozens of classic logic puzzles, free and ad-free."],
    ["Line Rider","https://www.linerider.com","Draw a track and watch a little sledder ride it."],
    ["GeoFS","https://www.geo-fs.com","A free flight simulator over real satellite maps."],
    ["Lichess","https://lichess.org","Free chess, with puzzles and no ads."]]],
  "Reading & ideas":["📚",[
    ["Random Wikipedia article","https://en.wikipedia.org/wiki/Special:Random","A different article every single time."],
    ["Unusual Wikipedia articles","https://en.wikipedia.org/wiki/Wikipedia:Unusual_articles","Wikipedia's own list of its strangest entries."],
    ["The Pudding","https://pudding.cool","Visual essays that explain culture with data."],
    ["Letters of Note","https://lettersofnote.com","Remarkable letters, telegrams and notes from history."],
    ["Futility Closet","https://www.futilitycloset.com","Curiosities from history, language and logic."],
    ["The Marginalian","https://www.themarginalian.org","Long essays on art, science and how to live."],
    ["Aeon","https://aeon.co","Thoughtful essays on philosophy, science and culture."],
    ["Wait But Why","https://waitbutwhy.com","Very long, very illustrated explanations of big ideas."],
    ["Project Gutenberg","https://www.gutenberg.org","Tens of thousands of free public domain books."],
    ["Damn Interesting","https://www.damninteresting.com","Long, well-researched true stories from history and science."],
    ["Longreads","https://longreads.com","The best long-form writing from around the web."],
    ["Kottke.org","https://kottke.org","One of the web's oldest blogs, still finding great things daily."],
    ["Nautilus","https://nautil.us","Science stories told with a literary touch."],
    ["Stanford Encyclopedia of Philosophy","https://plato.stanford.edu","Deep, free entries on every corner of philosophy."],
    ["Paul Graham's essays","https://paulgraham.com/articles.html","Short essays on startups, writing and how to think."],
    ["Lapham's Quarterly","https://www.laphamsquarterly.org","History told through excerpts from across the centuries."],
    ["Poetry Foundation","https://www.poetryfoundation.org","Thousands of poems, plus essays and poet biographies."]]],
  "Nature & calm":["🌿",[
    ["Explore.org Live Cams","https://explore.org/livecams","Live feeds of bears, eagles, puppies and reefs."],
    ["xeno-canto","https://xeno-canto.org","Bird songs recorded all over the world."],
    ["A Soft Murmur","https://asoftmurmur.com","Mix rain, waves, fire and wind into your own ambience."],
    ["Rainy Mood","https://rainymood.com","Just rain. It helps."],
    ["iNaturalist","https://www.inaturalist.org","See what plants and animals people are spotting near you."],
    ["Sandspiel","https://sandspiel.club","A falling-sand sandbox with water, plants and fire."],
    ["myNoise","https://mynoise.net","Beautifully crafted soundscapes you can tune with sliders."],
    ["Noisli","https://www.noisli.com","Mix background sounds for focus or rest."],
    ["All About Birds","https://www.allaboutbirds.org","Cornell's guide to birds, with songs and photos."],
    ["OneZoom Tree of Life","https://www.onezoom.org","Zoom through the whole tree of life, species by species."],
    ["Ventusky","https://www.ventusky.com","Gorgeous animated weather maps of the whole planet."],
    ["BBC Sound Effects","https://sound-effects.bbcrewind.co.uk","Thousands of BBC nature and ambient recordings."],
    ["Mushroom Observer","https://mushroomobserver.org","A community record of mushrooms spotted in the wild."]]],
  "Words & language":["📝",[
    ["Etymonline","https://www.etymonline.com","Where words come from, and how their meanings drifted."],
    ["Visuwords","https://visuwords.com","A dictionary drawn as a web of connected words."],
    ["OneLook Thesaurus","https://www.onelook.com/thesaurus/","Describe an idea and find the word for it."],
    ["Omniglot","https://www.omniglot.com","The writing systems and languages of the world."],
    ["Wordnik","https://www.wordnik.com","A dictionary with real example sentences for every word."],
    ["The Phrase Finder","https://www.phrases.org.uk","The meanings and origins of common sayings."],
    ["Language Log","https://languagelog.ldc.upenn.edu","Linguists blogging about language in the news and the wild."],
    ["Endangered Languages","https://www.endangeredlanguages.com","A map of languages at risk of disappearing."]]],
  "History":["🏛️",[
    ["Histography","https://histography.io","Every event on Wikipedia, laid out on a timeline you can explore."],
    ["Chronas","https://chronas.org","A world map of empires and borders, year by year."],
    ["Old Bailey Online","https://www.oldbaileyonline.org","200,000 London criminal trials from 1674 to 1913."],
    ["e-codices","https://www.e-codices.unifr.ch","Medieval manuscripts from Swiss libraries, zoomable page by page."],
    ["Map of Early Modern London","https://mapoflondon.uvic.ca","Shakespeare-era London, street by street."],
    ["Digital Public Library of America","https://dp.la","Photos, letters and records from American libraries and museums."],
    ["Europeana","https://www.europeana.eu","Millions of artworks, books and recordings from European archives."],
    ["Library of Congress Free to Use","https://www.loc.gov/free-to-use/","Historic photos and prints anyone can reuse."]]]
};


// Left out in family-safe mode: grown-up films, music with explicit lyrics, alcohol, open chat with
// strangers, and archives or random pickers that can land anywhere. Erring on the side of caution.
const NOT_FOR_KIDS = new Set([
  "https://www.windows93.net",
  "https://imsdb.com",
  "https://www.scriptslug.com",
  "https://film-grab.com",
  "https://www.sensesofcinema.com",
  "https://brightlightsfilm.com",
  "https://mubi.com/notebook",
  "https://archive.org/details/feature_films",
  "https://archive.org/details/prelinger",
  "https://www.openculture.com/freemoviesonline",
  "https://www.movie-map.com",
  "https://tvtropes.org",
  "https://www.artofthetitle.com",
  "https://www.criterion.com/closet-picks",
  "https://www.nts.live",
  "https://daily.bandcamp.com",
  "https://www.whosampled.com",
  "https://onlinesequencer.net",
  "https://www.diffordsguide.com",
  "https://winefolly.com",
  "https://hyperallergic.com",
  "https://neocities.org/browse",
  "https://gifcities.org",
  "https://wiby.me",
  "https://web.archive.org",
  "https://oldweb.today",
  "https://theoldnet.com",
  "https://en.wikipedia.org/wiki/Special:Random",
  "https://en.wikipedia.org/wiki/Wikipedia:Unusual_articles",
  "https://longreads.com",
  "https://kottke.org",
  "https://www.damninteresting.com",
  "https://waitbutwhy.com",
  "https://lettersofnote.com",
  "https://www.laphamsquarterly.org",
  "https://languagelog.ldc.upenn.edu",
  "https://www.oldbaileyonline.org",
  "https://lichess.org"
]);

if (typeof self !== 'undefined') { self.SITES = SITES; self.NOT_FOR_KIDS = NOT_FOR_KIDS; }
