// Built-in starter library, used before (or without) an API key.
const SITES = {
  "Weird & wonderful":["🌀",[
    ["The Useless Web","https://theuselessweb.com","A button that sends you to a pointless website. Stumbling, inside stumbling."],
    ["Pointer Pointer","https://pointerpointer.com","Leave your cursor anywhere and a real photo of someone pointing at it appears."],
    ["Staggering Beauty","https://www.staggeringbeauty.com","Wiggle your mouse. Then wiggle it faster. (Flashing lights warning.)"],
    ["Hacker Typer","https://hackertyper.net","Mash your keyboard and look like a movie hacker."],
    ["Zoomquilt","https://zoomquilt.org","An endless painted zoom that never reaches the bottom."],
    ["Koalas to the Max","https://koalastothemax.com","Hover over circles to split them until a picture emerges."],
    ["Eel Slap","https://eelslap.com","Exactly what it says. Move your mouse to slap a man with an eel."],
    ["Cameron's World","https://www.cameronsworld.net","A collage of GeoCities pages, glitter GIFs and all."],
    ["Windows 93","https://www.windows93.net","A fake operating system full of jokes and tiny programs."]]],
  "Music":["🎧",[
    ["Radio Garden","https://radio.garden","Spin a globe and tune into live radio stations anywhere on Earth."],
    ["Radiooooo","https://radiooooo.com","Choose a country and a decade, then listen to what was playing."],
    ["Every Noise at Once","https://everynoise.com","A map of thousands of music genres you can click to hear."],
    ["Chrome Music Lab","https://musiclab.chromeexperiments.com","Playful experiments for making and understanding music."],
    ["Incredibox","https://www.incredibox.com","Drag sounds onto a beatboxing crew to build a track."],
    ["Musicmap","https://musicmap.info","A genealogy of popular music genres, with example tracks."],
    ["Patatap","https://patatap.com","Every key on your keyboard makes a sound and an animation."],
    ["WhoSampled","https://www.whosampled.com","Trace which songs sampled, covered, or remixed which."],
    ["Typatone","https://typatone.com","Type a sentence and hear it turned into a melody."]]],
  "Film & TV":["🎞️",[
    ["Film-Grab","https://film-grab.com","A huge archive of beautiful stills, browsable by film."],
    ["Art of the Title","https://www.artofthetitle.com","Deep dives into film and TV title sequences."],
    ["IMSDb","https://imsdb.com","Read the scripts of hundreds of movies."],
    ["Prelinger Archives","https://archive.org/details/prelinger","Ephemeral films: ads, educational shorts, and industrial reels."],
    ["Feature Films on the Internet Archive","https://archive.org/details/feature_films","Public domain features you can watch right now."],
    ["Criterion Closet Picks","https://www.criterion.com/closet-picks","Directors and actors raid the Criterion closet and explain their picks."],
    ["Senses of Cinema","https://www.sensesofcinema.com","A long-running online journal of serious film writing."],
    ["Bright Lights Film Journal","https://brightlightsfilm.com","Film criticism with a taste for the offbeat."]]],
  "Art & design":["🎨",[
    ["The Public Domain Review","https://publicdomainreview.org","Essays and oddities from the history of art, literature and ideas."],
    ["Sanzo Wada's Color Combinations","https://sanzo-wada.dmbk.io","A 1930s Japanese color dictionary, made interactive."],
    ["Fonts In Use","https://fontsinuse.com","An archive of typography spotted in the wild."],
    ["Weave Silk","http://weavesilk.com","Draw with symmetrical, flowing strands of light."],
    ["Quick, Draw!","https://quickdraw.withgoogle.com","Doodle something and a neural network tries to guess it."],
    ["Google Arts & Culture","https://artsandculture.google.com","Museum collections, zoomable artworks and odd experiments."],
    ["Cooper Hewitt Collection","https://collection.cooperhewitt.org","Browse the Smithsonian's design museum, even by color."],
    ["This Is Sand","https://thisissand.com","Pour colored sand into slow, satisfying layered pictures."]]],
  "Science & space":["🔭",[
    ["Scale of the Universe","https://htwins.net/scale2/","Zoom from the Planck length to the whole observable universe."],
    ["If the Moon Were One Pixel","https://joshworth.com/dev/pixelspace/pixelspace_solarsystem.html","Scroll across a to-scale solar system. It takes a while."],
    ["The Deep Sea","https://neal.fun/deep-sea/","Scroll down into the ocean and meet what lives at each depth."],
    ["Astronomy Picture of the Day","https://apod.nasa.gov","A new space image every day since 1995, with an explanation."],
    ["Earth Wind Map","https://earth.nullschool.net","Live wind, ocean currents and weather swirling around the globe."],
    ["Stellarium Web","https://stellarium-web.org","A planetarium in your browser showing tonight's sky."],
    ["Bartosz Ciechanowski","https://ciechanow.ski","Stunning interactive explainers on how things work."],
    ["Explorable Explanations","https://explorabl.es","A collection of learn-by-playing interactive essays."]]],
  "Nostalgia":["📼",[
    ["The Restart Page","https://www.therestartpage.com","Old operating systems rebooting, one after another."],
    ["Space Jam (1996)","https://www.spacejam.com/1996/","The original movie website, still preserved as it was."],
    ["Museum of Endangered Sounds","https://savethesounds.info","Dial-up modems, Tamagotchis and other vanishing noises."],
    ["oldweb.today","https://oldweb.today","Browse archived websites through emulated old browsers."],
    ["Poolsuite FM","https://poolsuite.net","Summery radio inside a retro desktop interface."],
    ["Wayback Machine","https://web.archive.org","Look up any website as it was years ago."],
    ["Chronicling America","https://chroniclingamerica.loc.gov","Historic American newspapers, searchable page by page."],
    ["Old Maps Online","https://www.oldmapsonline.org","Find historical maps of anywhere you've ever lived."]]],
  "Travel & places":["🧭",[
    ["WindowSwap","https://www.window-swap.com","Look out a stranger's window somewhere in the world."],
    ["Drive & Listen","https://drivenlisten.com","Ride through a city's streets with its local radio on."],
    ["City Walks","https://citywalks.live","Walk through cities around the world, in real footage."],
    ["Earth View","https://earthview.withgoogle.com","Striking satellite images of the planet's landscapes."],
    ["Atlas Obscura","https://www.atlasobscura.com","The world's hidden wonders and strange places."],
    ["Cities and Memory","https://citiesandmemory.com","A global sound map of field recordings and their reimaginings."]]],
  "Food":["🍓",[
    ["Gastro Obscura","https://www.atlasobscura.com/gastro","Unusual foods, drinks, and culinary history."],
    ["TasteAtlas","https://www.tasteatlas.com","A world map of traditional dishes and where they come from."],
    ["The Food Timeline","https://www.foodtimeline.org","When and where foods and recipes first appeared."],
    ["Supercook","https://www.supercook.com","Enter what's in your kitchen and find recipes that use it."],
    ["Serious Eats","https://www.seriouseats.com","Recipes with the science of why they work."]]],
  "Games & play":["🎲",[
    ["Little Alchemy 2","https://littlealchemy2.com","Combine elements to discover hundreds of things."],
    ["Universal Paperclips","https://www.decisionproblem.com/paperclips/","Make paperclips. Then make more. It gets out of hand."],
    ["A Dark Room","https://adarkroom.doublespeakgames.com","A minimalist text adventure that keeps unfolding."],
    ["The Password Game","https://neal.fun/password-game/","Create a password that follows increasingly absurd rules."],
    ["Spend Bill Gates' Money","https://neal.fun/spend/","Try to spend a few billion dollars."],
    ["Slow Roads","https://slowroads.io","An endless, calming procedurally generated drive."],
    ["Semantle","https://semantle.com","Guess the secret word by how close in meaning you get."],
    ["2048","https://play2048.co","Slide tiles, merge numbers, lose an afternoon."]]],
  "Reading & ideas":["📚",[
    ["Random Wikipedia article","https://en.wikipedia.org/wiki/Special:Random","A different article every single time."],
    ["Unusual Wikipedia articles","https://en.wikipedia.org/wiki/Wikipedia:Unusual_articles","Wikipedia's own list of its strangest entries."],
    ["The Pudding","https://pudding.cool","Visual essays that explain culture with data."],
    ["Letters of Note","https://lettersofnote.com","Remarkable letters, telegrams and notes from history."],
    ["Futility Closet","https://www.futilitycloset.com","Curiosities from history, language and logic."],
    ["The Marginalian","https://www.themarginalian.org","Long essays on art, science and how to live."],
    ["Aeon","https://aeon.co","Thoughtful essays on philosophy, science and culture."],
    ["Wait But Why","https://waitbutwhy.com","Very long, very illustrated explanations of big ideas."],
    ["Project Gutenberg","https://www.gutenberg.org","Tens of thousands of free public domain books."]]],
  "Nature & calm":["🌿",[
    ["Explore.org Live Cams","https://explore.org/livecams","Live feeds of bears, eagles, puppies and reefs."],
    ["xeno-canto","https://xeno-canto.org","Bird songs recorded all over the world."],
    ["A Soft Murmur","https://asoftmurmur.com","Mix rain, waves, fire and wind into your own ambience."],
    ["Rainy Mood","https://rainymood.com","Just rain. It helps."],
    ["iNaturalist","https://www.inaturalist.org","See what plants and animals people are spotting near you."],
    ["Sandspiel","https://sandspiel.club","A falling-sand sandbox with water, plants and fire."]]]
};


if (typeof self !== 'undefined') self.SITES = SITES;
